//Acá interactuamos con nuestra API con esta extensión "REST CLIENT"

//RUTAS
### Inicio
GET http://localhost:4000

### Devuelve todas las tareas que hay según la cantidad de objetos que le pedimos con el size. Paginación
GET http://localhost:4000/api/tasks?size=3

### find por ID
GET http://localhost:4000/api/tasks/60283c0156a2c66f21bb5c36

### find por ID y borrarla, este ID ya fue borrado
DELETE  http://localhost:4000/api/tasks/602a8cbd19f2ea884d8a44da

### Crea una tarea
POST http://localhost:4000/api/tasks
    Content-Type: application/json

{
    "title":"Probando Validaciones en el controlador",
    "descripcion": "Usamos un ternario para verificar el valor en la respuesta.",
    "done": true
}

### Devuelve todas las tareas done: true
GET http://localhost:4000/api/tasks/done

###
PUT http://localhost:4000/api/tasks/60296c7c73d7457d507e4a6f
    Content-Type: application/json

{
    "title": "Probando PUT ",
    "descripcion": "Esta tarea fue actualizada mediante un método PUT",
    "done": true
}
