

//Acá interactuamos con nuestra API con esta extensión "REST CLIENT"

//RUTAS

###
GET http://localhost:4000

###
GET http://localhost:4000/api/tasks

###
POST http://localhost:4000/api/tasks
    Content-Type: application/json

{
    "title": "Hacer lo que me pasaron.",
    "descripcion": "Tarea dada por la directora.",
    "done": "false"
}